// Basic Imports
import Head from "next/head";
import { NextPage } from "next";

// Components Imports
import Header from "@/website/Header";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Spendify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
